version: '3.8'
services:
  dev-db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: fbla
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    networks:
      - freecodecamp
  test-db:
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: fbla
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    networks:
      - freecodecamp
networks:
  freecodecamp:
